import Head from "next/head";
import Link from "next/link";
import { useState } from "react";
import { api } from "~/utils/api";

export default function Home() {
  const [search, setSearch] = useState();

  const hello = api.example.hello.useQuery({ text: "from tRPC" });
  const allData = api.example.getAll.useQuery();

  const handleSearch = (e) => {
    setSearch(e.target.value);
    console.log(search);
  };

  if (!allData.isFetched) {
    return <h1>Loading...</h1>;
  }

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center bg-gradient-to-b from-[#2e026d] to-[#15162c] text-white">
        <input
          type="text"
          className="w-44 text-black"
          value={search}
          onChange={handleSearch}
        ></input>

        <table>
          <tr>
            <th>First Name</th>
            <th>Last Name</th>
            <th>Company</th>
            <th>Country</th>
            <th>Phone</th>
          </tr>
          {allData.data?.map((object) => {
            return (
              <tr key={object.id}>
                <td>{object.First_Name}</td>
                <td>{object.Last_Name}</td>
                <td>{object.Company}</td>
                <td>{object.Country}</td>
                <td>{object.Phone_1}</td>
              </tr>
            );
          })}
        </table>
      </main>
    </>
  );
}
